# Generated by Django 4.2.15 on 2024-08-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProbInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prob_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("dimensions", models.IntegerField()),
                ("objectives", models.IntegerField()),
                ("value_vector", models.JSONField()),
                ("weight_matrix", models.JSONField()),
            ],
        ),
    ]
