# Generated by Django 4.2.15 on 2024-08-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("algMag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alginfo",
            name="prams",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="algMag.parminfo",
            ),
        ),
    ]
