# Generated by Django 4.2.15 on 2024-08-21 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("algMag", "0004_rename_parminfo_praminfo"),
    ]

    operations = [
        migrations.RemoveField(model_name="alginfo", name="prams",),
        migrations.AddField(
            model_name="praminfo",
            name="algorithm",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="algMag.alginfo",
            ),
        ),
    ]
