# Generated by Django 4.2.15 on 2024-08-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlgResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algorithm_name", models.CharField(max_length=255)),
                ("problem_name", models.CharField(max_length=255)),
                ("run_id", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="GenResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algorithm_name", models.CharField(max_length=255)),
                ("coding", models.JSONField()),
                ("gen_num", models.IntegerField()),
                ("obj_value", models.FloatField()),
                ("problem_instance_name", models.CharField(max_length=255)),
                ("run_id", models.IntegerField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
    ]
