# Generated by Django 4.2.15 on 2024-08-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userMag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo", name="role", field=models.IntegerField(default=0),
        ),
    ]
