# Generated by Django 4.2.15 on 2024-08-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="姓名")),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "普通用户"), (1, "管理员")], verbose_name="权限"
                    ),
                ),
                ("email", models.CharField(max_length=255, verbose_name="邮箱")),
            ],
        ),
    ]
