# Generated by Django 4.2.15 on 2024-08-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("algMag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alg_name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AlgResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algorithm_name", models.CharField(max_length=255)),
                ("problem_name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("algorithms", models.TextField(blank=True, null=True)),
                ("problems", models.TextField(blank=True, null=True)),
                ("execution_count", models.IntegerField()),
                ("start_time", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProbInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prob_name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("dimensions", models.IntegerField()),
                ("objectives", models.IntegerField()),
                ("value_vector", models.JSONField()),
                ("weight_matrix", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="PramInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parm_name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                (
                    "algorithm",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algMag.alginfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algorithm_name", models.CharField(max_length=255)),
                ("coding", models.JSONField()),
                ("gen_num", models.IntegerField()),
                ("obj_value", models.FloatField()),
                ("problem_instance_name", models.CharField(max_length=255)),
                ("end_time", models.DateTimeField()),
                (
                    "run",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algMag.algresult",
                    ),
                ),
            ],
        ),
    ]
